name: 🧹 PR Lint Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint-check:
    runs-on: ubuntu-latest
    name: Check Linting on Frontend and Backend

    env:
      # ✅ Dummy env vars to bypass Zod checks in env.ts/env.js
      NODE_ENV: development
      CLERK_SECRET_KEY: dummy_secret_key
      NEXT_PUBLIC_SERVER_API_URL: http://localhost:3000/api
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: dummy_publishable_key
      RESEND_API_KEY: dummy_resend_key
      DATABASE_URL: postgresql://user:password@localhost:5432/giglance
      PORT: 5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies (Frontend)
        run: |
          cd frontend
          yarn install --frozen-lockfile

      - name: Run Lint (Frontend)
        run: |
          cd frontend
          yarn lint
        continue-on-error: true
        id: lint-frontend

      - name: Install Dependencies (Backend)
        run: |
          cd backend
          yarn install --frozen-lockfile

      - name: Run Lint (Backend)
        run: |
          cd backend
          yarn lint
        continue-on-error: true
        id: lint-backend

      - name: Check if any linting failed
        if: steps.lint-frontend.outcome == 'failure' || steps.lint-backend.outcome == 'failure'
        run: |
          echo "Linting failed. Posting a comment and closing the PR..."
          gh pr comment ${{ github.event.pull_request.number }} --body $'🚫 Hey @${{ github.actor }}, your PR failed lint checks.\n\nPlease run `yarn lint` in both `frontend` and `backend` folders locally and fix the issues before opening a PR.\n\nRefer to the [contribution guidelines](https://github.com/upes-open/OSoC-25-Giglance/blob/main/.github/CONTRIBUTING.md) for linting rules.'
          gh pr edit "${{ github.event.pull_request.number }}" --add-label "Lint failed"
          gh pr close "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Linting passed
        if: steps.lint-frontend.outcome == 'success' && steps.lint-backend.outcome == 'success'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "✅ Great job @${{ github.actor }}! Linting passed for both frontend and backend."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
